### ISSUE TITLE
🐋 add service mailcatcher in docker

### ISSUE THREAD

**Issue by isaqueveras** [isaqueveras/power-sso#70]
```yaml
mailcatcher:
  container_name: mailcatcher
  image: sj26/mailcatcher
  expose:
    - 1025
    - 1080
  ports:
    - 1025:1025
    - 1080:1080
```
